notifications:
  email: true

sudo: required

language: generic

services:
  - docker

before_install:
  - export SPLUNK_HOME="/opt/splunk"
  - export RANDOM_PASSWORD=$(openssl rand -hex 20)
  # Pull docker image
  - docker pull splunk/splunk
  # Add DOCKER to iptables, 1/10 times this is needed, force 0 exit status
  - sudo iptables -N DOCKER || true
  - sudo iptables -I INPUT -p tcp --dport $SPLKMGMT -j ACCEPT || true
  # Start Docker container
  - docker create --name autobuild_$SPLKMGMT --hostname autobuild -v /opt/splunk/etc/apps
    -e "SPLUNK_START_ARGS=--accept-license" -p "$SPLKMGMT:8089" -e "SPLUNK_USER=splunk"
    -e SPLUNK_CMD='edit user admin -password random_password -role admin -auth admin:changeme'
    splunk/splunk:$SPLUNK_VERSION
  - echo "`date -u` - Starting container"
  - docker start autobuild_$SPLKMGMT
  - for i in `seq 0 5 100`;
    do if curl --fail -k -u admin:random_password https://localhost:$SPLKMGMT/services/server/info &> /dev/null;
    then break;
    fi;
    echo "`date -u` - Waited $i seconds for container to start" ; sleep 5;
    if [ 100 -eq "$i" ]; then exit -1 ; fi ; done
  - echo "`date -u` - Changing default admin password"
  - docker exec autobuild_$SPLKMGMT entrypoint.sh splunk edit user admin -password $RANDOM_PASSWORD -role admin -auth admin:random_password

install:
  - echo "`date -u` - Installing TA"
  - docker cp $TRAVIS_BUILD_DIR autobuild_$SPLKMGMT:/opt/splunk/etc/apps/
  - docker exec autobuild_$SPLKMGMT mkdir /opt/splunk/etc/apps/TA-mailclient/local/
  - docker exec autobuild_$SPLKMGMT bash -c "echo -e '[mail://$EMAIL_ACCOUNT]\npassword=$MB_PASSWD\nprotocol = $PROTO\ndisabled = 0\nhost = $MAILSERVER\ninclude_headers = 0\ninterval = 30\nis_secure = $IS_SECURE\nmailbox_cleanup = readonly\nmailserver = $MAILSERVER\nsourcetype = mail:pop3\n' > /opt/splunk/etc/apps/TA-mailclient/local/inputs.conf"
  - docker exec autobuild_$SPLKMGMT chown -R splunk.splunk /opt/splunk/etc/apps/TA-mailclient/ 
  - echo "`date -u` - Restarting splunk"
  - docker exec autobuild_$SPLKMGMT entrypoint.sh splunk restart
  # - docker exec autobuild_$SPLKMGMT entrypoint.sh splunk set log-level ExecProcessor -level DEBUG -auth admin:$RANDOM_PASSWORD
  # - docker exec autobuild_$SPLKMGMT entrypoint.sh splunk set log-level ModInputs -level DEBUG -auth admin:$RANDOM_PASSWORD

script:
  - echo "`date -u` - Checking if TA was installed successfully and enabled"
  - curl -s --fail -k -u admin:$RANDOM_PASSWORD https://localhost:$SPLKMGMT/services/apps/local/TA-mailclient | grep "\"disabled\">0"
  - echo "`date -u` - Checking if modular input is not broken"
  - curl --fail -k -u admin:$RANDOM_PASSWORD https://localhost:$SPLKMGMT/services/data/modular-inputs/mail &>/dev/null
  - echo "`date -u` - Checking if test modular input is not disabled"
  - curl -s --fail -k -u admin:$RANDOM_PASSWORD https://localhost:$SPLKMGMT/servicesNS/nobody/TA-mailclient/data/inputs/mail/pop_to_splunk%40gmx.com | grep "\"disabled\">0"
  - sleep 45
  - echo "`date -u` - Check if password encryption is working"
  - docker exec autobuild_$SPLKMGMT grep -B1 encrypted /opt/splunk/etc/apps/TA-mailclient/local/inputs.conf
  - echo "`date -u` - Check if a test mail was pulled"
  - for i in `seq 0 5 40`; do echo "Waited $i seconds for pop3 results" ;
    if curl -s --get -k -u admin:$RANDOM_PASSWORD https://localhost:$SPLKMGMT/services/search/jobs/export --data-urlencode search="search index=main sourcetype=mail* | table _time sourcetype source _raw" -d output_mode=raw -d earliest="-365d" -d latest=now ;
    then break; fi; sleep 5; done
  - echo "Check internal logs for Execprocessor events"
  - curl --get -k -u admin:$RANDOM_PASSWORD https://localhost:$SPLKMGMT/services/search/jobs/export --data-urlencode search="search index=_internal sourcetype=splunkd (component=ModularInputs OR component=ExecProcessor) mail.py | head 10 | table _time _raw" -d output_mode=csv -d earliest="-1h" -d latest=now

env:
    # - SPLUNK_VERSION=6.6.1 SPLKMGMT=9900
    - SPLUNK_VERSION=latest SPLKMGMT=9900 IS_SECURE=0 MAILSERVER=pop.aol.com PROTO=POP3 EMAIL_ACCOUNT=pop_to_splunk@aol.com
    - SPLUNK_VERSION=latest SPLKMGMT=9901 IS_SECURE=1 MAILSERVER=pop.gmx.com PROTO=POP3 EMAIL_ACCOUNT=pop_to_splunk@gmx.com
    - SPLUNK_VERSION=latest SPLKMGMT=9902 IS_SECURE=0 MAILSERVER=imap.aol.com PROTO=IMAP EMAIL_ACCOUNT=pop_to_splunk@aol.com
    - SPLUNK_VERSION=latest SPLKMGMT=9903 IS_SECURE=1 MAILSERVER=imap.gmx.com PROTO=IMAP EMAIL_ACCOUNT=pop_to_splunk@gmx.com
